=== dasher-project/DasherCore/Data/alphabets/alphabet.dtd
<!-- alphabet defintion for Dasher -->

<!ELEMENT alphabet (group*)>
<!ATTLIST alphabet name CDATA #REQUIRED> <!-- unique name that can be referenced in Dasher to choose this alphabet -->
<!ATTLIST alphabet orientation (LR|RL|TB|BT) #REQUIRED> <!-- orientation in which this alphabet is typed. Example: LR=Left-to-Right -->
<!ATTLIST alphabet conversionMode (none|mandarin|routingContextInsensitive|routingContextSensitive) "none"> <!-- conversion mode that is used internally to spawn a decoder that can handle phonetic writing -->
<!ATTLIST alphabet trainingFilename CDATA #IMPLIED> <!-- filename that is referenced for training the language model -->
<!ATTLIST alphabet colorsName CDATA "Default"> <!-- unique name of the color schema that should be used by default -->

<!-- Logical groups of symbols, eg name="lowercase" -->
<!ELEMENT group (node*|group*)>
<!ATTLIST group colorInfoName CDATA #IMPLIED>
<!ATTLIST group name CDATA #IMPLIED>
<!ATTLIST group label CDATA #IMPLIED>

<!-- Single symbols -->
<!ELEMENT node (textCharAction*|deleteTextAction*|moveCursorAction*|fixedTTSAction*|contextTTSAction*|repeatTTSAction*|stopTTSAction*|pauseDasherAction*|stopDasherAction*|copyToClipboardAction*|atspiAction*|keyboardAction*|socketOutputAction*|changeSettingAction*)>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node text CDATA #IMPLIED> <!-- represents the text that is output and also used for training, defaults to the same value as label -->
<!ATTLIST node fixedProbability CDATA #IMPLIED>
<!ATTLIST node speedFactor CDATA #IMPLIED>

<!-- Actions that can happen if the node is selected -->

<!-- Text output: -->
<!ELEMENT textCharAction EMPTY>
<!ATTLIST textCharAction unicode CDATA #IMPLIED> <!-- If the Unicode value is unspecified, the label will be used to determine it. If the label is empty or consists of more than one character, an error will be thrown. -->

<!ELEMENT deleteTextAction EMPTY>
<!ATTLIST deleteTextAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)", or "all" -->

<!ELEMENT moveCursorAction EMPTY>
<!ATTLIST moveCursorAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)" -->

<!-- Text-to-Speech: -->
<!ELEMENT fixedTTSAction EMPTY>
<!ATTLIST fixedTTSAction text CDATA #REQUIRED> <!-- speaks out the given text -->

<!ELEMENT contextTTSAction EMPTY>
<!ATTLIST contextTTSAction context (word|sentence|paragraph|all) #REQUIRED> <!-- Reads out the last word/sentence/paragraph/all -->

<!ELEMENT repeatTTSAction EMPTY> <!-- Repeats the last TTS output -->

<!ELEMENT stopTTSAction EMPTY> <!-- Stops any currently ongoing TTS -->

<!-- Dasher-internal: -->
<!ELEMENT pauseDasherAction EMPTY> <!-- Stops any currently ongoing TTS -->
<!ATTLIST pauseDasherAction time CDATA #IMPLIED> <!-- Pauses Dasher for the given time, or stops forever if time is unspecified -->

<!ELEMENT stopDasherAction EMPTY> <!-- Stops Dasher and pauses input -->

<!-- Clipboard: -->
<!ELEMENT copyToClipboardAction EMPTY>
<!ATTLIST copyToClipboardAction context CDATA "all"> <!-- Can be "all", "new", "word", "sentence", "paragraph" -->

<!-- System/application control: -->

<!ELEMENT changeSettingAction EMPTY>
<!ATTLIST changeSettingAction settingsName CDATA #REQUIRED> <!-- Stringname of the Setting -->
<!ATTLIST changeSettingAction doValue CDATA #IMPLIED> <!-- New Value of the Setting in case of selection -->
<!ATTLIST changeSettingAction undoValue CDATA #IMPLIED> <!-- New Value of the Setting in case of deselection -->

<!-- These two actions enable triggering any action in an application that can be bound to a keyboard shortcut or is accessible
     via the Assistive Technology Service Provider Interface (AT-SPI). Anything else probably isn't technically feasible. -->
<!ELEMENT atspiAction EMPTY>
<!ATTLIST atspiAction action CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->
<!ATTLIST atspiAction undoAction CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->

<!ELEMENT keyboardAction EMPTY>
<!ATTLIST keyboardAction key CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction press CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction release CDATA #IMPLIED> <!-- As above, but only performing the release -->
<!ATTLIST keyboardAction undoKey CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction undoPress CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction undoRelease CDATA #IMPLIED> <!-- As above, but only performing the release -->

<!-- External actions: -->
<!-- Similar to the socket input option, this action enables connecting Dasher to other accessibility tools, sending messages that the other tool can process. -->
<!ELEMENT socketOutputAction EMPTY>
<!ATTLIST socketOutputAction socketName CDATA #IMPLIED>
<!ATTLIST socketOutputAction doString CDATA #IMPLIED>
<!ATTLIST socketOutputAction undoString CDATA #IMPLIED>
<!ATTLIST socketOutputAction suppressNewline CDATA #IMPLIED>

<!-- Especially for the last two, it probably makes sense to add a windowTitle attribute to nodes: -->
<!-- <node label="New Tab" windowTitle=".*(Firefox|Chrome|Edge).*" fixedProbability="0.02"> Only shows this node if the title of the currently focused window matches the given regex. -->
 <!--  <atspiAction action="NewTab"/> -->
<!-- </node> -->

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.ngiemboon.nnh-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Ngiemboon (WorldAlphabets)" orientation="LR" trainingFilename="training_wa_nnh_Latn.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="a">
      <textCharAction />
    </node>
    <node label="á">
      <textCharAction />
    </node>
    <node label="à">
      <textCharAction />
    </node>
    <node label="â">
      <textCharAction />
    </node>
    <node label="ǎ">
      <textCharAction />
    </node>
    <node label="b">
      <textCharAction />
    </node>
    <node label="c">
      <textCharAction />
    </node>
    <node label="d">
      <textCharAction />
    </node>
    <node label="e">
      <textCharAction />
    </node>
    <node label="é">
      <textCharAction />
    </node>
    <node label="è">
      <textCharAction />
    </node>
    <node label="ê">
      <textCharAction />
    </node>
    <node label="ě">
      <textCharAction />
    </node>
    <node label="ɛ">
      <textCharAction />
    </node>
    <node label="f">
      <textCharAction />
    </node>
    <node label="g">
      <textCharAction />
    </node>
    <node label="h">
      <textCharAction />
    </node>
    <node label="i">
      <textCharAction />
    </node>
    <node label="í">
      <textCharAction />
    </node>
    <node label="ì">
      <textCharAction />
    </node>
    <node label="j">
      <textCharAction />
    </node>
    <node label="k">
      <textCharAction />
    </node>
    <node label="l">
      <textCharAction />
    </node>
    <node label="m">
      <textCharAction />
    </node>
    <node label="ḿ">
      <textCharAction />
    </node>
    <node label="n">
      <textCharAction />
    </node>
    <node label="ń">
      <textCharAction />
    </node>
    <node label="ŋ">
      <textCharAction />
    </node>
    <node label="o">
      <textCharAction />
    </node>
    <node label="ó">
      <textCharAction />
    </node>
    <node label="ò">
      <textCharAction />
    </node>
    <node label="ô">
      <textCharAction />
    </node>
    <node label="ǒ">
      <textCharAction />
    </node>
    <node label="ɔ">
      <textCharAction />
    </node>
    <node label="p">
      <textCharAction />
    </node>
    <node label="s">
      <textCharAction />
    </node>
    <node label="t">
      <textCharAction />
    </node>
    <node label="u">
      <textCharAction />
    </node>
    <node label="ú">
      <textCharAction />
    </node>
    <node label="ù">
      <textCharAction />
    </node>
    <node label="û">
      <textCharAction />
    </node>
    <node label="ǔ">
      <textCharAction />
    </node>
    <node label="ʉ">
      <textCharAction />
    </node>
    <node label="v">
      <textCharAction />
    </node>
    <node label="w">
      <textCharAction />
    </node>
    <node label="ẅ">
      <textCharAction />
    </node>
    <node label="y">
      <textCharAction />
    </node>
    <node label="ÿ">
      <textCharAction />
    </node>
    <node label="z">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="A">
      <textCharAction />
    </node>
    <node label="Á">
      <textCharAction />
    </node>
    <node label="À">
      <textCharAction />
    </node>
    <node label="Â">
      <textCharAction />
    </node>
    <node label="Ǎ">
      <textCharAction />
    </node>
    <node label="B">
      <textCharAction />
    </node>
    <node label="C">
      <textCharAction />
    </node>
    <node label="D">
      <textCharAction />
    </node>
    <node label="E">
      <textCharAction />
    </node>
    <node label="É">
      <textCharAction />
    </node>
    <node label="È">
      <textCharAction />
    </node>
    <node label="Ê">
      <textCharAction />
    </node>
    <node label="Ě">
      <textCharAction />
    </node>
    <node label="Ɛ">
      <textCharAction />
    </node>
    <node label="F">
      <textCharAction />
    </node>
    <node label="G">
      <textCharAction />
    </node>
    <node label="H">
      <textCharAction />
    </node>
    <node label="I">
      <textCharAction />
    </node>
    <node label="Í">
      <textCharAction />
    </node>
    <node label="Ì">
      <textCharAction />
    </node>
    <node label="J">
      <textCharAction />
    </node>
    <node label="K">
      <textCharAction />
    </node>
    <node label="L">
      <textCharAction />
    </node>
    <node label="M">
      <textCharAction />
    </node>
    <node label="Ḿ">
      <textCharAction />
    </node>
    <node label="N">
      <textCharAction />
    </node>
    <node label="Ń">
      <textCharAction />
    </node>
    <node label="Ŋ">
      <textCharAction />
    </node>
    <node label="O">
      <textCharAction />
    </node>
    <node label="Ó">
      <textCharAction />
    </node>
    <node label="Ò">
      <textCharAction />
    </node>
    <node label="Ô">
      <textCharAction />
    </node>
    <node label="Ǒ">
      <textCharAction />
    </node>
    <node label="Ɔ">
      <textCharAction />
    </node>
    <node label="P">
      <textCharAction />
    </node>
    <node label="S">
      <textCharAction />
    </node>
    <node label="T">
      <textCharAction />
    </node>
    <node label="U">
      <textCharAction />
    </node>
    <node label="Ú">
      <textCharAction />
    </node>
    <node label="Ù">
      <textCharAction />
    </node>
    <node label="Û">
      <textCharAction />
    </node>
    <node label="Ǔ">
      <textCharAction />
    </node>
    <node label="Ʉ">
      <textCharAction />
    </node>
    <node label="V">
      <textCharAction />
    </node>
    <node label="W">
      <textCharAction />
    </node>
    <node label="Ẅ">
      <textCharAction />
    </node>
    <node label="Y">
      <textCharAction />
    </node>
    <node label="Ÿ">
      <textCharAction />
    </node>
    <node label="Z">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
  </group>
  <group name="Digits" colorInfoName="digits">
    <node label="0">
      <textCharAction />
    </node>
    <node label="1">
      <textCharAction />
    </node>
    <node label="2">
      <textCharAction />
    </node>
    <node label="3">
      <textCharAction />
    </node>
    <node label="4">
      <textCharAction />
    </node>
    <node label="5">
      <textCharAction />
    </node>
    <node label="6">
      <textCharAction />
    </node>
    <node label="7">
      <textCharAction />
    </node>
    <node label="8">
      <textCharAction />
    </node>
    <node label="9">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.divehi.dv-Thaa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Divehi (WorldAlphabets)" orientation="RL" trainingFilename="" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="ހ">
      <textCharAction />
    </node>
    <node label="ށ">
      <textCharAction />
    </node>
    <node label="ނ">
      <textCharAction />
    </node>
    <node label="ރ">
      <textCharAction />
    </node>
    <node label="ބ">
      <textCharAction />
    </node>
    <node label="ޅ">
      <textCharAction />
    </node>
    <node label="ކ">
      <textCharAction />
    </node>
    <node label="އ">
      <textCharAction />
    </node>
    <node label="ވ">
      <textCharAction />
    </node>
    <node label="މ">
      <textCharAction />
    </node>
    <node label="ފ">
      <textCharAction />
    </node>
    <node label="ދ">
      <textCharAction />
    </node>
    <node label="ތ">
      <textCharAction />
    </node>
    <node label="ލ">
      <textCharAction />
    </node>
    <node label="ގ">
      <textCharAction />
    </node>
    <node label="ޏ">
      <textCharAction />
    </node>
    <node label="ސ">
      <textCharAction />
    </node>
    <node label="ޑ">
      <textCharAction />
    </node>
    <node label="ޒ">
      <textCharAction />
    </node>
    <node label="ޓ">
      <textCharAction />
    </node>
    <node label="ޔ">
      <textCharAction />
    </node>
    <node label="ޕ">
      <textCharAction />
    </node>
    <node label="ޖ">
      <textCharAction />
    </node>
    <node label="ޗ">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="ހ">
      <textCharAction />
    </node>
    <node label="ށ">
      <textCharAction />
    </node>
    <node label="ނ">
      <textCharAction />
    </node>
    <node label="ރ">
      <textCharAction />
    </node>
    <node label="ބ">
      <textCharAction />
    </node>
    <node label="ޅ">
      <textCharAction />
    </node>
    <node label="ކ">
      <textCharAction />
    </node>
    <node label="އ">
      <textCharAction />
    </node>
    <node label="ވ">
      <textCharAction />
    </node>
    <node label="މ">
      <textCharAction />
    </node>
    <node label="ފ">
      <textCharAction />
    </node>
    <node label="ދ">
      <textCharAction />
    </node>
    <node label="ތ">
      <textCharAction />
    </node>
    <node label="ލ">
      <textCharAction />
    </node>
    <node label="ގ">
      <textCharAction />
    </node>
    <node label="ޏ">
      <textCharAction />
    </node>
    <node label="ސ">
      <textCharAction />
    </node>
    <node label="ޑ">
      <textCharAction />
    </node>
    <node label="ޒ">
      <textCharAction />
    </node>
    <node label="ޓ">
      <textCharAction />
    </node>
    <node label="ޔ">
      <textCharAction />
    </node>
    <node label="ޕ">
      <textCharAction />
    </node>
    <node label="ޖ">
      <textCharAction />
    </node>
    <node label="ޗ">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.asturian.ast-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Asturian (WorldAlphabets)" orientation="LR" trainingFilename="training_wa_ast_Latn.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="a">
      <textCharAction />
    </node>
    <node label="á">
      <textCharAction />
    </node>
    <node label="b">
      <textCharAction />
    </node>
    <node label="c">
      <textCharAction />
    </node>
    <node label="d">
      <textCharAction />
    </node>
    <node label="e">
      <textCharAction />
    </node>
    <node label="é">
      <textCharAction />
    </node>
    <node label="f">
      <textCharAction />
    </node>
    <node label="g">
      <textCharAction />
    </node>
    <node label="h">
      <textCharAction />
    </node>
    <node label="ḥ">
      <textCharAction />
    </node>
    <node label="i">
      <textCharAction />
    </node>
    <node label="í">
      <textCharAction />
    </node>
    <node label="l">
      <textCharAction />
    </node>
    <node label="ḷ">
      <textCharAction />
    </node>
    <node label="m">
      <textCharAction />
    </node>
    <node label="n">
      <textCharAction />
    </node>
    <node label="ñ">
      <textCharAction />
    </node>
    <node label="o">
      <textCharAction />
    </node>
    <node label="ó">
      <textCharAction />
    </node>
    <node label="p">
      <textCharAction />
    </node>
    <node label="q">
      <textCharAction />
    </node>
    <node label="r">
      <textCharAction />
    </node>
    <node label="s">
      <textCharAction />
    </node>
    <node label="t">
      <textCharAction />
    </node>
    <node label="u">
      <textCharAction />
    </node>
    <node label="ú">
      <textCharAction />
    </node>
    <node label="ü">
      <textCharAction />
    </node>
    <node label="v">
      <textCharAction />
    </node>
    <node label="x">
      <textCharAction />
    </node>
    <node label="y">
      <textCharAction />
    </node>
    <node label="z">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="A">
      <textCharAction />
    </node>
    <node label="Á">
      <textCharAction />
    </node>
    <node label="B">
      <textCharAction />
    </node>
    <node label="C">
      <textCharAction />
    </node>
    <node label="D">
      <textCharAction />
    </node>
    <node label="E">
      <textCharAction />
    </node>
    <node label="É">
      <textCharAction />
    </node>
    <node label="F">
      <textCharAction />
    </node>
    <node label="G">
      <textCharAction />
    </node>
    <node label="H">
      <textCharAction />
    </node>
    <node label="Ḥ">
      <textCharAction />
    </node>
    <node label="I">
      <textCharAction />
    </node>
    <node label="Í">
      <textCharAction />
    </node>
    <node label="L">
      <textCharAction />
    </node>
    <node label="Ḷ">
      <textCharAction />
    </node>
    <node label="M">
      <textCharAction />
    </node>
    <node label="N">
      <textCharAction />
    </node>
    <node label="Ñ">
      <textCharAction />
    </node>
    <node label="O">
      <textCharAction />
    </node>
    <node label="Ó">
      <textCharAction />
    </node>
    <node label="P">
      <textCharAction />
    </node>
    <node label="Q">
      <textCharAction />
    </node>
    <node label="R">
      <textCharAction />
    </node>
    <node label="S">
      <textCharAction />
    </node>
    <node label="T">
      <textCharAction />
    </node>
    <node label="U">
      <textCharAction />
    </node>
    <node label="Ú">
      <textCharAction />
    </node>
    <node label="Ü">
      <textCharAction />
    </node>
    <node label="V">
      <textCharAction />
    </node>
    <node label="X">
      <textCharAction />
    </node>
    <node label="Y">
      <textCharAction />
    </node>
    <node label="Z">
      <textCharAction />
    </node>
  </group>
  <group name="Digits" colorInfoName="digits">
    <node label="0">
      <textCharAction />
    </node>
    <node label="1">
      <textCharAction />
    </node>
    <node label="2">
      <textCharAction />
    </node>
    <node label="3">
      <textCharAction />
    </node>
    <node label="4">
      <textCharAction />
    </node>
    <node label="5">
      <textCharAction />
    </node>
    <node label="6">
      <textCharAction />
    </node>
    <node label="7">
      <textCharAction />
    </node>
    <node label="8">
      <textCharAction />
    </node>
    <node label="9">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.quechua.qu-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Quechua (WorldAlphabets)" orientation="LR" trainingFilename="training_wa_qu_Latn.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="a">
      <textCharAction />
    </node>
    <node label="c">
      <textCharAction />
    </node>
    <node label="h">
      <textCharAction />
    </node>
    <node label="i">
      <textCharAction />
    </node>
    <node label="k">
      <textCharAction />
    </node>
    <node label="l">
      <textCharAction />
    </node>
    <node label="m">
      <textCharAction />
    </node>
    <node label="n">
      <textCharAction />
    </node>
    <node label="ñ">
      <textCharAction />
    </node>
    <node label="p">
      <textCharAction />
    </node>
    <node label="q">
      <textCharAction />
    </node>
    <node label="s">
      <textCharAction />
    </node>
    <node label="t">
      <textCharAction />
    </node>
    <node label="u">
      <textCharAction />
    </node>
    <node label="w">
      <textCharAction />
    </node>
    <node label="y">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="A">
      <textCharAction />
    </node>
    <node label="C">
      <textCharAction />
    </node>
    <node label="H">
      <textCharAction />
    </node>
    <node label="I">
      <textCharAction />
    </node>
    <node label="K">
      <textCharAction />
    </node>
    <node label="L">
      <textCharAction />
    </node>
    <node label="M">
      <textCharAction />
    </node>
    <node label="N">
      <textCharAction />
    </node>
    <node label="Ñ">
      <textCharAction />
    </node>
    <node label="P">
      <textCharAction />
    </node>
    <node label="Q">
      <textCharAction />
    </node>
    <node label="S">
      <textCharAction />
    </node>
    <node label="T">
      <textCharAction />
    </node>
    <node label="U">
      <textCharAction />
    </node>
    <node label="W">
      <textCharAction />
    </node>
    <node label="Y">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.serbian.sr-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Serbian (WorldAlphabets)" orientation="LR" trainingFilename="" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="a">
      <textCharAction />
    </node>
    <node label="b">
      <textCharAction />
    </node>
    <node label="c">
      <textCharAction />
    </node>
    <node label="d">
      <textCharAction />
    </node>
    <node label="e">
      <textCharAction />
    </node>
    <node label="f">
      <textCharAction />
    </node>
    <node label="g">
      <textCharAction />
    </node>
    <node label="h">
      <textCharAction />
    </node>
    <node label="i">
      <textCharAction />
    </node>
    <node label="j">
      <textCharAction />
    </node>
    <node label="k">
      <textCharAction />
    </node>
    <node label="l">
      <textCharAction />
    </node>
    <node label="m">
      <textCharAction />
    </node>
    <node label="n">
      <textCharAction />
    </node>
    <node label="o">
      <textCharAction />
    </node>
    <node label="p">
      <textCharAction />
    </node>
    <node label="r">
      <textCharAction />
    </node>
    <node label="s">
      <textCharAction />
    </node>
    <node label="t">
      <textCharAction />
    </node>
    <node label="u">
      <textCharAction />
    </node>
    <node label="v">
      <textCharAction />
    </node>
    <node label="z">
      <textCharAction />
    </node>
    <node label="ć">
      <textCharAction />
    </node>
    <node label="č">
      <textCharAction />
    </node>
    <node label="đ">
      <textCharAction />
    </node>
    <node label="š">
      <textCharAction />
    </node>
    <node label="ž">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="A">
      <textCharAction />
    </node>
    <node label="B">
      <textCharAction />
    </node>
    <node label="C">
      <textCharAction />
    </node>
    <node label="D">
      <textCharAction />
    </node>
    <node label="E">
      <textCharAction />
    </node>
    <node label="F">
      <textCharAction />
    </node>
    <node label="G">
      <textCharAction />
    </node>
    <node label="H">
      <textCharAction />
    </node>
    <node label="I">
      <textCharAction />
    </node>
    <node label="J">
      <textCharAction />
    </node>
    <node label="K">
      <textCharAction />
    </node>
    <node label="L">
      <textCharAction />
    </node>
    <node label="M">
      <textCharAction />
    </node>
    <node label="N">
      <textCharAction />
    </node>
    <node label="O">
      <textCharAction />
    </node>
    <node label="P">
      <textCharAction />
    </node>
    <node label="R">
      <textCharAction />
    </node>
    <node label="S">
      <textCharAction />
    </node>
    <node label="T">
      <textCharAction />
    </node>
    <node label="U">
      <textCharAction />
    </node>
    <node label="V">
      <textCharAction />
    </node>
    <node label="Z">
      <textCharAction />
    </node>
    <node label="Ć">
      <textCharAction />
    </node>
    <node label="Č">
      <textCharAction />
    </node>
    <node label="Đ">
      <textCharAction />
    </node>
    <node label="Š">
      <textCharAction />
    </node>
    <node label="Ž">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>
