=== dasher-project/DasherCore/Data/alphabets/alphabet.dtd
<!-- alphabet defintion for Dasher -->

<!ELEMENT alphabet (group*)>
<!ATTLIST alphabet name CDATA #REQUIRED> <!-- unique name that can be referenced in Dasher to choose this alphabet -->
<!ATTLIST alphabet orientation (LR|RL|TB|BT) #REQUIRED> <!-- orientation in which this alphabet is typed. Example: LR=Left-to-Right -->
<!ATTLIST alphabet conversionMode (none|mandarin|routingContextInsensitive|routingContextSensitive) "none"> <!-- conversion mode that is used internally to spawn a decoder that can handle phonetic writing -->
<!ATTLIST alphabet trainingFilename CDATA #IMPLIED> <!-- filename that is referenced for training the language model -->
<!ATTLIST alphabet colorsName CDATA "Default"> <!-- unique name of the color schema that should be used by default -->

<!-- Logical groups of symbols, eg name="lowercase" -->
<!ELEMENT group (node*|group*)>
<!ATTLIST group colorInfoName CDATA #IMPLIED>
<!ATTLIST group name CDATA #IMPLIED>
<!ATTLIST group label CDATA #IMPLIED>

<!-- Single symbols -->
<!ELEMENT node (textCharAction*|deleteTextAction*|moveCursorAction*|fixedTTSAction*|contextTTSAction*|repeatTTSAction*|stopTTSAction*|pauseDasherAction*|stopDasherAction*|copyToClipboardAction*|atspiAction*|keyboardAction*|socketOutputAction*|changeSettingAction*)>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node text CDATA #IMPLIED> <!-- represents the text that is output and also used for training, defaults to the same value as label -->
<!ATTLIST node fixedProbability CDATA #IMPLIED>
<!ATTLIST node speedFactor CDATA #IMPLIED>

<!-- Actions that can happen if the node is selected -->

<!-- Text output: -->
<!ELEMENT textCharAction EMPTY>
<!ATTLIST textCharAction unicode CDATA #IMPLIED> <!-- If the Unicode value is unspecified, the label will be used to determine it. If the label is empty or consists of more than one character, an error will be thrown. -->

<!ELEMENT deleteTextAction EMPTY>
<!ATTLIST deleteTextAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)", or "all" -->

<!ELEMENT moveCursorAction EMPTY>
<!ATTLIST moveCursorAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)" -->

<!-- Text-to-Speech: -->
<!ELEMENT fixedTTSAction EMPTY>
<!ATTLIST fixedTTSAction text CDATA #REQUIRED> <!-- speaks out the given text -->

<!ELEMENT contextTTSAction EMPTY>
<!ATTLIST contextTTSAction context (word|sentence|paragraph|all) #REQUIRED> <!-- Reads out the last word/sentence/paragraph/all -->

<!ELEMENT repeatTTSAction EMPTY> <!-- Repeats the last TTS output -->

<!ELEMENT stopTTSAction EMPTY> <!-- Stops any currently ongoing TTS -->

<!-- Dasher-internal: -->
<!ELEMENT pauseDasherAction EMPTY> <!-- Stops any currently ongoing TTS -->
<!ATTLIST pauseDasherAction time CDATA #IMPLIED> <!-- Pauses Dasher for the given time, or stops forever if time is unspecified -->

<!ELEMENT stopDasherAction EMPTY> <!-- Stops Dasher and pauses input -->

<!-- Clipboard: -->
<!ELEMENT copyToClipboardAction EMPTY>
<!ATTLIST copyToClipboardAction context CDATA "all"> <!-- Can be "all", "new", "word", "sentence", "paragraph" -->

<!-- System/application control: -->

<!ELEMENT changeSettingAction EMPTY>
<!ATTLIST changeSettingAction settingsName CDATA #REQUIRED> <!-- Stringname of the Setting -->
<!ATTLIST changeSettingAction doValue CDATA #IMPLIED> <!-- New Value of the Setting in case of selection -->
<!ATTLIST changeSettingAction undoValue CDATA #IMPLIED> <!-- New Value of the Setting in case of deselection -->

<!-- These two actions enable triggering any action in an application that can be bound to a keyboard shortcut or is accessible
     via the Assistive Technology Service Provider Interface (AT-SPI). Anything else probably isn't technically feasible. -->
<!ELEMENT atspiAction EMPTY>
<!ATTLIST atspiAction action CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->
<!ATTLIST atspiAction undoAction CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->

<!ELEMENT keyboardAction EMPTY>
<!ATTLIST keyboardAction key CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction press CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction release CDATA #IMPLIED> <!-- As above, but only performing the release -->
<!ATTLIST keyboardAction undoKey CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction undoPress CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction undoRelease CDATA #IMPLIED> <!-- As above, but only performing the release -->

<!-- External actions: -->
<!-- Similar to the socket input option, this action enables connecting Dasher to other accessibility tools, sending messages that the other tool can process. -->
<!ELEMENT socketOutputAction EMPTY>
<!ATTLIST socketOutputAction socketName CDATA #IMPLIED>
<!ATTLIST socketOutputAction doString CDATA #IMPLIED>
<!ATTLIST socketOutputAction undoString CDATA #IMPLIED>
<!ATTLIST socketOutputAction suppressNewline CDATA #IMPLIED>

<!-- Especially for the last two, it probably makes sense to add a windowTitle attribute to nodes: -->
<!-- <node label="New Tab" windowTitle=".*(Firefox|Chrome|Edge).*" fixedProbability="0.02"> Only shows this node if the title of the currently focused window matches the given regex. -->
 <!--  <atspiAction action="NewTab"/> -->
<!-- </node> -->

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.ukrainian.uk-Cyrl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Ukrainian (WorldAlphabets)" orientation="LR" trainingFilename="training_wa_uk_Cyrl.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="а">
      <textCharAction />
    </node>
    <node label="б">
      <textCharAction />
    </node>
    <node label="в">
      <textCharAction />
    </node>
    <node label="г">
      <textCharAction />
    </node>
    <node label="ґ">
      <textCharAction />
    </node>
    <node label="д">
      <textCharAction />
    </node>
    <node label="е">
      <textCharAction />
    </node>
    <node label="є">
      <textCharAction />
    </node>
    <node label="ж">
      <textCharAction />
    </node>
    <node label="з">
      <textCharAction />
    </node>
    <node label="и">
      <textCharAction />
    </node>
    <node label="і">
      <textCharAction />
    </node>
    <node label="ї">
      <textCharAction />
    </node>
    <node label="й">
      <textCharAction />
    </node>
    <node label="к">
      <textCharAction />
    </node>
    <node label="л">
      <textCharAction />
    </node>
    <node label="м">
      <textCharAction />
    </node>
    <node label="н">
      <textCharAction />
    </node>
    <node label="о">
      <textCharAction />
    </node>
    <node label="п">
      <textCharAction />
    </node>
    <node label="р">
      <textCharAction />
    </node>
    <node label="с">
      <textCharAction />
    </node>
    <node label="т">
      <textCharAction />
    </node>
    <node label="у">
      <textCharAction />
    </node>
    <node label="ф">
      <textCharAction />
    </node>
    <node label="х">
      <textCharAction />
    </node>
    <node label="ц">
      <textCharAction />
    </node>
    <node label="ч">
      <textCharAction />
    </node>
    <node label="ш">
      <textCharAction />
    </node>
    <node label="щ">
      <textCharAction />
    </node>
    <node label="ю">
      <textCharAction />
    </node>
    <node label="я">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
    <node label="ь">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="А">
      <textCharAction />
    </node>
    <node label="Б">
      <textCharAction />
    </node>
    <node label="В">
      <textCharAction />
    </node>
    <node label="Г">
      <textCharAction />
    </node>
    <node label="Ґ">
      <textCharAction />
    </node>
    <node label="Д">
      <textCharAction />
    </node>
    <node label="Е">
      <textCharAction />
    </node>
    <node label="Є">
      <textCharAction />
    </node>
    <node label="Ж">
      <textCharAction />
    </node>
    <node label="З">
      <textCharAction />
    </node>
    <node label="И">
      <textCharAction />
    </node>
    <node label="І">
      <textCharAction />
    </node>
    <node label="Ї">
      <textCharAction />
    </node>
    <node label="Й">
      <textCharAction />
    </node>
    <node label="К">
      <textCharAction />
    </node>
    <node label="Л">
      <textCharAction />
    </node>
    <node label="М">
      <textCharAction />
    </node>
    <node label="Н">
      <textCharAction />
    </node>
    <node label="О">
      <textCharAction />
    </node>
    <node label="П">
      <textCharAction />
    </node>
    <node label="Р">
      <textCharAction />
    </node>
    <node label="С">
      <textCharAction />
    </node>
    <node label="Т">
      <textCharAction />
    </node>
    <node label="У">
      <textCharAction />
    </node>
    <node label="Ф">
      <textCharAction />
    </node>
    <node label="Х">
      <textCharAction />
    </node>
    <node label="Ц">
      <textCharAction />
    </node>
    <node label="Ч">
      <textCharAction />
    </node>
    <node label="Ш">
      <textCharAction />
    </node>
    <node label="Щ">
      <textCharAction />
    </node>
    <node label="Ю">
      <textCharAction />
    </node>
    <node label="Я">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
    <node label="Ь">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.syriac.syr-Syrc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Syriac (WorldAlphabets)" orientation="RL" trainingFilename="training_wa_syr_Syrc.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="ܐ">
      <textCharAction />
    </node>
    <node label="ܒ">
      <textCharAction />
    </node>
    <node label="ܓ">
      <textCharAction />
    </node>
    <node label="ܕ">
      <textCharAction />
    </node>
    <node label="ܗ">
      <textCharAction />
    </node>
    <node label="ܘ">
      <textCharAction />
    </node>
    <node label="ܙ">
      <textCharAction />
    </node>
    <node label="ܚ">
      <textCharAction />
    </node>
    <node label="ܛ">
      <textCharAction />
    </node>
    <node label="ܝ">
      <textCharAction />
    </node>
    <node label="ܟ">
      <textCharAction />
    </node>
    <node label="ܠ">
      <textCharAction />
    </node>
    <node label="ܡ">
      <textCharAction />
    </node>
    <node label="ܢ">
      <textCharAction />
    </node>
    <node label="ܣ">
      <textCharAction />
    </node>
    <node label="ܥ">
      <textCharAction />
    </node>
    <node label="ܦ">
      <textCharAction />
    </node>
    <node label="ܨ">
      <textCharAction />
    </node>
    <node label="ܩ">
      <textCharAction />
    </node>
    <node label="ܪ">
      <textCharAction />
    </node>
    <node label="ܫ">
      <textCharAction />
    </node>
    <node label="ܬ">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="ܐ">
      <textCharAction />
    </node>
    <node label="ܒ">
      <textCharAction />
    </node>
    <node label="ܓ">
      <textCharAction />
    </node>
    <node label="ܕ">
      <textCharAction />
    </node>
    <node label="ܗ">
      <textCharAction />
    </node>
    <node label="ܘ">
      <textCharAction />
    </node>
    <node label="ܙ">
      <textCharAction />
    </node>
    <node label="ܚ">
      <textCharAction />
    </node>
    <node label="ܛ">
      <textCharAction />
    </node>
    <node label="ܝ">
      <textCharAction />
    </node>
    <node label="ܟ">
      <textCharAction />
    </node>
    <node label="ܠ">
      <textCharAction />
    </node>
    <node label="ܡ">
      <textCharAction />
    </node>
    <node label="ܢ">
      <textCharAction />
    </node>
    <node label="ܣ">
      <textCharAction />
    </node>
    <node label="ܥ">
      <textCharAction />
    </node>
    <node label="ܦ">
      <textCharAction />
    </node>
    <node label="ܨ">
      <textCharAction />
    </node>
    <node label="ܩ">
      <textCharAction />
    </node>
    <node label="ܪ">
      <textCharAction />
    </node>
    <node label="ܫ">
      <textCharAction />
    </node>
    <node label="ܬ">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.filipino.tl-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Filipino (WorldAlphabets)" orientation="LR" trainingFilename="training_wa_tl_Latn.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="ᜀ">
      <textCharAction />
    </node>
    <node label="ᜁ">
      <textCharAction />
    </node>
    <node label="ᜂ">
      <textCharAction />
    </node>
    <node label="ᜃ">
      <textCharAction />
    </node>
    <node label="ᜄ">
      <textCharAction />
    </node>
    <node label="ᜅ">
      <textCharAction />
    </node>
    <node label="ᜆ">
      <textCharAction />
    </node>
    <node label="ᜇ">
      <textCharAction />
    </node>
    <node label="ᜈ">
      <textCharAction />
    </node>
    <node label="ᜉ">
      <textCharAction />
    </node>
    <node label="ᜊ">
      <textCharAction />
    </node>
    <node label="ᜋ">
      <textCharAction />
    </node>
    <node label="ᜌ">
      <textCharAction />
    </node>
    <node label="ᜎ">
      <textCharAction />
    </node>
    <node label="ᜏ">
      <textCharAction />
    </node>
    <node label="ᜐ">
      <textCharAction />
    </node>
    <node label="ᜑ">
      <textCharAction />
    </node>
    <node label="ᜒ">
      <textCharAction />
    </node>
    <node label="ᜓ">
      <textCharAction />
    </node>
    <node label="᜔">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="ᜀ">
      <textCharAction />
    </node>
    <node label="ᜁ">
      <textCharAction />
    </node>
    <node label="ᜂ">
      <textCharAction />
    </node>
    <node label="ᜃ">
      <textCharAction />
    </node>
    <node label="ᜄ">
      <textCharAction />
    </node>
    <node label="ᜅ">
      <textCharAction />
    </node>
    <node label="ᜆ">
      <textCharAction />
    </node>
    <node label="ᜇ">
      <textCharAction />
    </node>
    <node label="ᜈ">
      <textCharAction />
    </node>
    <node label="ᜉ">
      <textCharAction />
    </node>
    <node label="ᜊ">
      <textCharAction />
    </node>
    <node label="ᜋ">
      <textCharAction />
    </node>
    <node label="ᜌ">
      <textCharAction />
    </node>
    <node label="ᜎ">
      <textCharAction />
    </node>
    <node label="ᜏ">
      <textCharAction />
    </node>
    <node label="ᜐ">
      <textCharAction />
    </node>
    <node label="ᜑ">
      <textCharAction />
    </node>
    <node label="ᜒ">
      <textCharAction />
    </node>
    <node label="ᜓ">
      <textCharAction />
    </node>
    <node label="᜔">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.tasawaq.twq-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Tasawaq (WorldAlphabets)" orientation="LR" trainingFilename="training_wa_twq_Latn.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="a">
      <textCharAction />
    </node>
    <node label="ã">
      <textCharAction />
    </node>
    <node label="b">
      <textCharAction />
    </node>
    <node label="c">
      <textCharAction />
    </node>
    <node label="d">
      <textCharAction />
    </node>
    <node label="e">
      <textCharAction />
    </node>
    <node label="ẽ">
      <textCharAction />
    </node>
    <node label="f">
      <textCharAction />
    </node>
    <node label="g">
      <textCharAction />
    </node>
    <node label="h">
      <textCharAction />
    </node>
    <node label="i">
      <textCharAction />
    </node>
    <node label="j">
      <textCharAction />
    </node>
    <node label="k">
      <textCharAction />
    </node>
    <node label="l">
      <textCharAction />
    </node>
    <node label="m">
      <textCharAction />
    </node>
    <node label="n">
      <textCharAction />
    </node>
    <node label="ɲ">
      <textCharAction />
    </node>
    <node label="ŋ">
      <textCharAction />
    </node>
    <node label="o">
      <textCharAction />
    </node>
    <node label="õ">
      <textCharAction />
    </node>
    <node label="p">
      <textCharAction />
    </node>
    <node label="q">
      <textCharAction />
    </node>
    <node label="r">
      <textCharAction />
    </node>
    <node label="s">
      <textCharAction />
    </node>
    <node label="š">
      <textCharAction />
    </node>
    <node label="t">
      <textCharAction />
    </node>
    <node label="u">
      <textCharAction />
    </node>
    <node label="w">
      <textCharAction />
    </node>
    <node label="x">
      <textCharAction />
    </node>
    <node label="y">
      <textCharAction />
    </node>
    <node label="z">
      <textCharAction />
    </node>
    <node label="ž">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="A">
      <textCharAction />
    </node>
    <node label="Ã">
      <textCharAction />
    </node>
    <node label="B">
      <textCharAction />
    </node>
    <node label="C">
      <textCharAction />
    </node>
    <node label="D">
      <textCharAction />
    </node>
    <node label="E">
      <textCharAction />
    </node>
    <node label="Ẽ">
      <textCharAction />
    </node>
    <node label="F">
      <textCharAction />
    </node>
    <node label="G">
      <textCharAction />
    </node>
    <node label="H">
      <textCharAction />
    </node>
    <node label="I">
      <textCharAction />
    </node>
    <node label="J">
      <textCharAction />
    </node>
    <node label="K">
      <textCharAction />
    </node>
    <node label="L">
      <textCharAction />
    </node>
    <node label="M">
      <textCharAction />
    </node>
    <node label="N">
      <textCharAction />
    </node>
    <node label="Ɲ">
      <textCharAction />
    </node>
    <node label="Ŋ">
      <textCharAction />
    </node>
    <node label="O">
      <textCharAction />
    </node>
    <node label="Õ">
      <textCharAction />
    </node>
    <node label="P">
      <textCharAction />
    </node>
    <node label="Q">
      <textCharAction />
    </node>
    <node label="R">
      <textCharAction />
    </node>
    <node label="S">
      <textCharAction />
    </node>
    <node label="Š">
      <textCharAction />
    </node>
    <node label="T">
      <textCharAction />
    </node>
    <node label="U">
      <textCharAction />
    </node>
    <node label="W">
      <textCharAction />
    </node>
    <node label="X">
      <textCharAction />
    </node>
    <node label="Y">
      <textCharAction />
    </node>
    <node label="Z">
      <textCharAction />
    </node>
    <node label="Ž">
      <textCharAction />
    </node>
  </group>
  <group name="Digits" colorInfoName="digits">
    <node label="0">
      <textCharAction />
    </node>
    <node label="1">
      <textCharAction />
    </node>
    <node label="2">
      <textCharAction />
    </node>
    <node label="3">
      <textCharAction />
    </node>
    <node label="4">
      <textCharAction />
    </node>
    <node label="5">
      <textCharAction />
    </node>
    <node label="6">
      <textCharAction />
    </node>
    <node label="7">
      <textCharAction />
    </node>
    <node label="8">
      <textCharAction />
    </node>
    <node label="9">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.nko.nqo-Nkoo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="N’Ko (WorldAlphabets)" orientation="RL" trainingFilename="" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="ߊ">
      <textCharAction />
    </node>
    <node label="ߋ">
      <textCharAction />
    </node>
    <node label="ߌ">
      <textCharAction />
    </node>
    <node label="ߍ">
      <textCharAction />
    </node>
    <node label="ߎ">
      <textCharAction />
    </node>
    <node label="ߏ">
      <textCharAction />
    </node>
    <node label="ߐ">
      <textCharAction />
    </node>
    <node label="ߑ">
      <textCharAction />
    </node>
    <node label="ߒ">
      <textCharAction />
    </node>
    <node label="ߓ">
      <textCharAction />
    </node>
    <node label="ߔ">
      <textCharAction />
    </node>
    <node label="ߕ">
      <textCharAction />
    </node>
    <node label="ߖ">
      <textCharAction />
    </node>
    <node label="ߗ">
      <textCharAction />
    </node>
    <node label="ߘ">
      <textCharAction />
    </node>
    <node label="ߙ">
      <textCharAction />
    </node>
    <node label="ߚ">
      <textCharAction />
    </node>
    <node label="ߛ">
      <textCharAction />
    </node>
    <node label="ߜ">
      <textCharAction />
    </node>
    <node label="ߝ">
      <textCharAction />
    </node>
    <node label="ߞ">
      <textCharAction />
    </node>
    <node label="ߟ">
      <textCharAction />
    </node>
    <node label="ߠ">
      <textCharAction />
    </node>
    <node label="ߡ">
      <textCharAction />
    </node>
    <node label="ߢ">
      <textCharAction />
    </node>
    <node label="ߣ">
      <textCharAction />
    </node>
    <node label="ߤ">
      <textCharAction />
    </node>
    <node label="ߥ">
      <textCharAction />
    </node>
    <node label="ߦ">
      <textCharAction />
    </node>
    <node label="ߧ">
      <textCharAction />
    </node>
    <node label="ߴ">
      <textCharAction />
    </node>
    <node label="ߵ">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="ߊ">
      <textCharAction />
    </node>
    <node label="ߋ">
      <textCharAction />
    </node>
    <node label="ߌ">
      <textCharAction />
    </node>
    <node label="ߍ">
      <textCharAction />
    </node>
    <node label="ߎ">
      <textCharAction />
    </node>
    <node label="ߏ">
      <textCharAction />
    </node>
    <node label="ߐ">
      <textCharAction />
    </node>
    <node label="ߑ">
      <textCharAction />
    </node>
    <node label="ߒ">
      <textCharAction />
    </node>
    <node label="ߓ">
      <textCharAction />
    </node>
    <node label="ߔ">
      <textCharAction />
    </node>
    <node label="ߕ">
      <textCharAction />
    </node>
    <node label="ߖ">
      <textCharAction />
    </node>
    <node label="ߗ">
      <textCharAction />
    </node>
    <node label="ߘ">
      <textCharAction />
    </node>
    <node label="ߙ">
      <textCharAction />
    </node>
    <node label="ߚ">
      <textCharAction />
    </node>
    <node label="ߛ">
      <textCharAction />
    </node>
    <node label="ߜ">
      <textCharAction />
    </node>
    <node label="ߝ">
      <textCharAction />
    </node>
    <node label="ߞ">
      <textCharAction />
    </node>
    <node label="ߟ">
      <textCharAction />
    </node>
    <node label="ߠ">
      <textCharAction />
    </node>
    <node label="ߡ">
      <textCharAction />
    </node>
    <node label="ߢ">
      <textCharAction />
    </node>
    <node label="ߣ">
      <textCharAction />
    </node>
    <node label="ߤ">
      <textCharAction />
    </node>
    <node label="ߥ">
      <textCharAction />
    </node>
    <node label="ߦ">
      <textCharAction />
    </node>
    <node label="ߧ">
      <textCharAction />
    </node>
    <node label="ߴ">
      <textCharAction />
    </node>
    <node label="ߵ">
      <textCharAction />
    </node>
  </group>
  <group name="Digits" colorInfoName="digits">
    <node label="߀">
      <textCharAction />
    </node>
    <node label="߁">
      <textCharAction />
    </node>
    <node label="߂">
      <textCharAction />
    </node>
    <node label="߃">
      <textCharAction />
    </node>
    <node label="߄">
      <textCharAction />
    </node>
    <node label="߅">
      <textCharAction />
    </node>
    <node label="߆">
      <textCharAction />
    </node>
    <node label="߇">
      <textCharAction />
    </node>
    <node label="߈">
      <textCharAction />
    </node>
    <node label="߉">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>
