=== dasher-project/DasherCore/Data/alphabets/alphabet.dtd
<!-- alphabet defintion for Dasher -->

<!ELEMENT alphabet (group*)>
<!ATTLIST alphabet name CDATA #REQUIRED> <!-- unique name that can be referenced in Dasher to choose this alphabet -->
<!ATTLIST alphabet orientation (LR|RL|TB|BT) #REQUIRED> <!-- orientation in which this alphabet is typed. Example: LR=Left-to-Right -->
<!ATTLIST alphabet conversionMode (none|mandarin|routingContextInsensitive|routingContextSensitive) "none"> <!-- conversion mode that is used internally to spawn a decoder that can handle phonetic writing -->
<!ATTLIST alphabet trainingFilename CDATA #IMPLIED> <!-- filename that is referenced for training the language model -->
<!ATTLIST alphabet colorsName CDATA "Default"> <!-- unique name of the color schema that should be used by default -->

<!-- Logical groups of symbols, eg name="lowercase" -->
<!ELEMENT group (node*|group*)>
<!ATTLIST group colorInfoName CDATA #IMPLIED>
<!ATTLIST group name CDATA #IMPLIED>
<!ATTLIST group label CDATA #IMPLIED>

<!-- Single symbols -->
<!ELEMENT node (textCharAction*|deleteTextAction*|moveCursorAction*|fixedTTSAction*|contextTTSAction*|repeatTTSAction*|stopTTSAction*|pauseDasherAction*|stopDasherAction*|copyToClipboardAction*|atspiAction*|keyboardAction*|socketOutputAction*|changeSettingAction*)>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node text CDATA #IMPLIED> <!-- represents the text that is output and also used for training, defaults to the same value as label -->
<!ATTLIST node fixedProbability CDATA #IMPLIED>
<!ATTLIST node speedFactor CDATA #IMPLIED>

<!-- Actions that can happen if the node is selected -->

<!-- Text output: -->
<!ELEMENT textCharAction EMPTY>
<!ATTLIST textCharAction unicode CDATA #IMPLIED> <!-- If the Unicode value is unspecified, the label will be used to determine it. If the label is empty or consists of more than one character, an error will be thrown. -->

<!ELEMENT deleteTextAction EMPTY>
<!ATTLIST deleteTextAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)", or "all" -->

<!ELEMENT moveCursorAction EMPTY>
<!ATTLIST moveCursorAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)" -->

<!-- Text-to-Speech: -->
<!ELEMENT fixedTTSAction EMPTY>
<!ATTLIST fixedTTSAction text CDATA #REQUIRED> <!-- speaks out the given text -->

<!ELEMENT contextTTSAction EMPTY>
<!ATTLIST contextTTSAction context (word|sentence|paragraph|all) #REQUIRED> <!-- Reads out the last word/sentence/paragraph/all -->

<!ELEMENT repeatTTSAction EMPTY> <!-- Repeats the last TTS output -->

<!ELEMENT stopTTSAction EMPTY> <!-- Stops any currently ongoing TTS -->

<!-- Dasher-internal: -->
<!ELEMENT pauseDasherAction EMPTY> <!-- Stops any currently ongoing TTS -->
<!ATTLIST pauseDasherAction time CDATA #IMPLIED> <!-- Pauses Dasher for the given time, or stops forever if time is unspecified -->

<!ELEMENT stopDasherAction EMPTY> <!-- Stops Dasher and pauses input -->

<!-- Clipboard: -->
<!ELEMENT copyToClipboardAction EMPTY>
<!ATTLIST copyToClipboardAction context CDATA "all"> <!-- Can be "all", "new", "word", "sentence", "paragraph" -->

<!-- System/application control: -->

<!ELEMENT changeSettingAction EMPTY>
<!ATTLIST changeSettingAction settingsName CDATA #REQUIRED> <!-- Stringname of the Setting -->
<!ATTLIST changeSettingAction doValue CDATA #IMPLIED> <!-- New Value of the Setting in case of selection -->
<!ATTLIST changeSettingAction undoValue CDATA #IMPLIED> <!-- New Value of the Setting in case of deselection -->

<!-- These two actions enable triggering any action in an application that can be bound to a keyboard shortcut or is accessible
     via the Assistive Technology Service Provider Interface (AT-SPI). Anything else probably isn't technically feasible. -->
<!ELEMENT atspiAction EMPTY>
<!ATTLIST atspiAction action CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->
<!ATTLIST atspiAction undoAction CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->

<!ELEMENT keyboardAction EMPTY>
<!ATTLIST keyboardAction key CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction press CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction release CDATA #IMPLIED> <!-- As above, but only performing the release -->
<!ATTLIST keyboardAction undoKey CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction undoPress CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction undoRelease CDATA #IMPLIED> <!-- As above, but only performing the release -->

<!-- External actions: -->
<!-- Similar to the socket input option, this action enables connecting Dasher to other accessibility tools, sending messages that the other tool can process. -->
<!ELEMENT socketOutputAction EMPTY>
<!ATTLIST socketOutputAction socketName CDATA #IMPLIED>
<!ATTLIST socketOutputAction doString CDATA #IMPLIED>
<!ATTLIST socketOutputAction undoString CDATA #IMPLIED>
<!ATTLIST socketOutputAction suppressNewline CDATA #IMPLIED>

<!-- Especially for the last two, it probably makes sense to add a windowTitle attribute to nodes: -->
<!-- <node label="New Tab" windowTitle=".*(Firefox|Chrome|Edge).*" fixedProbability="0.02"> Only shows this node if the title of the currently focused window matches the given regex. -->
 <!--  <atspiAction action="NewTab"/> -->
<!-- </node> -->

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.tok.pisin.tpi-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Tok Pisin (WorldAlphabets)" orientation="LR" trainingFilename="" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="a">
      <textCharAction />
    </node>
    <node label="b">
      <textCharAction />
    </node>
    <node label="d">
      <textCharAction />
    </node>
    <node label="e">
      <textCharAction />
    </node>
    <node label="f">
      <textCharAction />
    </node>
    <node label="g">
      <textCharAction />
    </node>
    <node label="h">
      <textCharAction />
    </node>
    <node label="i">
      <textCharAction />
    </node>
    <node label="j">
      <textCharAction />
    </node>
    <node label="k">
      <textCharAction />
    </node>
    <node label="l">
      <textCharAction />
    </node>
    <node label="m">
      <textCharAction />
    </node>
    <node label="n">
      <textCharAction />
    </node>
    <node label="o">
      <textCharAction />
    </node>
    <node label="p">
      <textCharAction />
    </node>
    <node label="r">
      <textCharAction />
    </node>
    <node label="s">
      <textCharAction />
    </node>
    <node label="t">
      <textCharAction />
    </node>
    <node label="u">
      <textCharAction />
    </node>
    <node label="w">
      <textCharAction />
    </node>
    <node label="y">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="A">
      <textCharAction />
    </node>
    <node label="B">
      <textCharAction />
    </node>
    <node label="D">
      <textCharAction />
    </node>
    <node label="E">
      <textCharAction />
    </node>
    <node label="F">
      <textCharAction />
    </node>
    <node label="G">
      <textCharAction />
    </node>
    <node label="H">
      <textCharAction />
    </node>
    <node label="I">
      <textCharAction />
    </node>
    <node label="J">
      <textCharAction />
    </node>
    <node label="K">
      <textCharAction />
    </node>
    <node label="L">
      <textCharAction />
    </node>
    <node label="M">
      <textCharAction />
    </node>
    <node label="N">
      <textCharAction />
    </node>
    <node label="O">
      <textCharAction />
    </node>
    <node label="P">
      <textCharAction />
    </node>
    <node label="R">
      <textCharAction />
    </node>
    <node label="S">
      <textCharAction />
    </node>
    <node label="T">
      <textCharAction />
    </node>
    <node label="U">
      <textCharAction />
    </node>
    <node label="W">
      <textCharAction />
    </node>
    <node label="Y">
      <textCharAction />
    </node>
  </group>
  <group name="Digits" colorInfoName="digits">
    <node label="0">
      <textCharAction />
    </node>
    <node label="1">
      <textCharAction />
    </node>
    <node label="2">
      <textCharAction />
    </node>
    <node label="3">
      <textCharAction />
    </node>
    <node label="4">
      <textCharAction />
    </node>
    <node label="5">
      <textCharAction />
    </node>
    <node label="6">
      <textCharAction />
    </node>
    <node label="7">
      <textCharAction />
    </node>
    <node label="8">
      <textCharAction />
    </node>
    <node label="9">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.guarani.gn-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Guarani (WorldAlphabets)" orientation="LR" trainingFilename="training_wa_gn_Latn.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="a">
      <textCharAction />
    </node>
    <node label="ã">
      <textCharAction />
    </node>
    <node label="c">
      <textCharAction />
    </node>
    <node label="e">
      <textCharAction />
    </node>
    <node label="ẽ">
      <textCharAction />
    </node>
    <node label="h">
      <textCharAction />
    </node>
    <node label="i">
      <textCharAction />
    </node>
    <node label="ĩ">
      <textCharAction />
    </node>
    <node label="j">
      <textCharAction />
    </node>
    <node label="k">
      <textCharAction />
    </node>
    <node label="l">
      <textCharAction />
    </node>
    <node label="m">
      <textCharAction />
    </node>
    <node label="b">
      <textCharAction />
    </node>
    <node label="ñ">
      <textCharAction />
    </node>
    <node label="d">
      <textCharAction />
    </node>
    <node label="g">
      <textCharAction />
    </node>
    <node label="n">
      <textCharAction />
    </node>
    <node label="o">
      <textCharAction />
    </node>
    <node label="õ">
      <textCharAction />
    </node>
    <node label="p">
      <textCharAction />
    </node>
    <node label="r">
      <textCharAction />
    </node>
    <node label="s">
      <textCharAction />
    </node>
    <node label="t">
      <textCharAction />
    </node>
    <node label="u">
      <textCharAction />
    </node>
    <node label="ũ">
      <textCharAction />
    </node>
    <node label="v">
      <textCharAction />
    </node>
    <node label="y">
      <textCharAction />
    </node>
    <node label="ỹ">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="A">
      <textCharAction />
    </node>
    <node label="Ã">
      <textCharAction />
    </node>
    <node label="C">
      <textCharAction />
    </node>
    <node label="E">
      <textCharAction />
    </node>
    <node label="Ẽ">
      <textCharAction />
    </node>
    <node label="H">
      <textCharAction />
    </node>
    <node label="I">
      <textCharAction />
    </node>
    <node label="Ĩ">
      <textCharAction />
    </node>
    <node label="J">
      <textCharAction />
    </node>
    <node label="K">
      <textCharAction />
    </node>
    <node label="L">
      <textCharAction />
    </node>
    <node label="M">
      <textCharAction />
    </node>
    <node label="B">
      <textCharAction />
    </node>
    <node label="Ñ">
      <textCharAction />
    </node>
    <node label="D">
      <textCharAction />
    </node>
    <node label="G">
      <textCharAction />
    </node>
    <node label="N">
      <textCharAction />
    </node>
    <node label="O">
      <textCharAction />
    </node>
    <node label="Õ">
      <textCharAction />
    </node>
    <node label="P">
      <textCharAction />
    </node>
    <node label="R">
      <textCharAction />
    </node>
    <node label="S">
      <textCharAction />
    </node>
    <node label="T">
      <textCharAction />
    </node>
    <node label="U">
      <textCharAction />
    </node>
    <node label="Ũ">
      <textCharAction />
    </node>
    <node label="V">
      <textCharAction />
    </node>
    <node label="Y">
      <textCharAction />
    </node>
    <node label="Ỹ">
      <textCharAction />
    </node>
    <node label="ʼ">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.hanunoo.hnn-Latn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Hanunoo (WorldAlphabets)" orientation="LR" trainingFilename="" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="ᜠ">
      <textCharAction />
    </node>
    <node label="ᜡ">
      <textCharAction />
    </node>
    <node label="ᜢ">
      <textCharAction />
    </node>
    <node label="ᜣ">
      <textCharAction />
    </node>
    <node label="ᜤ">
      <textCharAction />
    </node>
    <node label="ᜥ">
      <textCharAction />
    </node>
    <node label="ᜦ">
      <textCharAction />
    </node>
    <node label="ᜧ">
      <textCharAction />
    </node>
    <node label="ᜨ">
      <textCharAction />
    </node>
    <node label="ᜩ">
      <textCharAction />
    </node>
    <node label="ᜪ">
      <textCharAction />
    </node>
    <node label="ᜫ">
      <textCharAction />
    </node>
    <node label="ᜬ">
      <textCharAction />
    </node>
    <node label="ᜭ">
      <textCharAction />
    </node>
    <node label="ᜮ">
      <textCharAction />
    </node>
    <node label="ᜯ">
      <textCharAction />
    </node>
    <node label="ᜰ">
      <textCharAction />
    </node>
    <node label="ᜱ">
      <textCharAction />
    </node>
    <node label="ᜲ">
      <textCharAction />
    </node>
    <node label="ᜳ">
      <textCharAction />
    </node>
    <node label="᜴">
      <textCharAction />
    </node>
    <node label="᜵">
      <textCharAction />
    </node>
    <node label="᜶">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="ᜠ">
      <textCharAction />
    </node>
    <node label="ᜡ">
      <textCharAction />
    </node>
    <node label="ᜢ">
      <textCharAction />
    </node>
    <node label="ᜣ">
      <textCharAction />
    </node>
    <node label="ᜤ">
      <textCharAction />
    </node>
    <node label="ᜥ">
      <textCharAction />
    </node>
    <node label="ᜦ">
      <textCharAction />
    </node>
    <node label="ᜧ">
      <textCharAction />
    </node>
    <node label="ᜨ">
      <textCharAction />
    </node>
    <node label="ᜩ">
      <textCharAction />
    </node>
    <node label="ᜪ">
      <textCharAction />
    </node>
    <node label="ᜫ">
      <textCharAction />
    </node>
    <node label="ᜬ">
      <textCharAction />
    </node>
    <node label="ᜭ">
      <textCharAction />
    </node>
    <node label="ᜮ">
      <textCharAction />
    </node>
    <node label="ᜯ">
      <textCharAction />
    </node>
    <node label="ᜰ">
      <textCharAction />
    </node>
    <node label="ᜱ">
      <textCharAction />
    </node>
    <node label="ᜲ">
      <textCharAction />
    </node>
    <node label="ᜳ">
      <textCharAction />
    </node>
    <node label="᜴">
      <textCharAction />
    </node>
    <node label="᜵">
      <textCharAction />
    </node>
    <node label="᜶">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>

=== dasher-project/DasherCore/Data/alphabets/autoConverted/alphabet.wa.kashmiri.ks-Arab.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Kashmiri (WorldAlphabets)" orientation="RL" trainingFilename="training_wa_ks_Arab.txt" colorsName="Default">
  <group name="Lower case" colorInfoName="lower case">
    <node label="ء">
      <textCharAction />
    </node>
    <node label="آ">
      <textCharAction />
    </node>
    <node label="أ">
      <textCharAction />
    </node>
    <node label="ٲ">
      <textCharAction />
    </node>
    <node label="ؤ">
      <textCharAction />
    </node>
    <node label="ا">
      <textCharAction />
    </node>
    <node label="ب">
      <textCharAction />
    </node>
    <node label="پ">
      <textCharAction />
    </node>
    <node label="ت">
      <textCharAction />
    </node>
    <node label="ث">
      <textCharAction />
    </node>
    <node label="ٹ">
      <textCharAction />
    </node>
    <node label="ج">
      <textCharAction />
    </node>
    <node label="چ">
      <textCharAction />
    </node>
    <node label="ح">
      <textCharAction />
    </node>
    <node label="خ">
      <textCharAction />
    </node>
    <node label="د">
      <textCharAction />
    </node>
    <node label="ذ">
      <textCharAction />
    </node>
    <node label="ڈ">
      <textCharAction />
    </node>
    <node label="ر">
      <textCharAction />
    </node>
    <node label="ز">
      <textCharAction />
    </node>
    <node label="ڑ">
      <textCharAction />
    </node>
    <node label="ژ">
      <textCharAction />
    </node>
    <node label="س">
      <textCharAction />
    </node>
    <node label="ش">
      <textCharAction />
    </node>
    <node label="ص">
      <textCharAction />
    </node>
    <node label="ض">
      <textCharAction />
    </node>
    <node label="ط">
      <textCharAction />
    </node>
    <node label="ظ">
      <textCharAction />
    </node>
    <node label="ع">
      <textCharAction />
    </node>
    <node label="غ">
      <textCharAction />
    </node>
    <node label="ف">
      <textCharAction />
    </node>
    <node label="ق">
      <textCharAction />
    </node>
    <node label="ک">
      <textCharAction />
    </node>
    <node label="گ">
      <textCharAction />
    </node>
    <node label="ل">
      <textCharAction />
    </node>
    <node label="م">
      <textCharAction />
    </node>
    <node label="ن">
      <textCharAction />
    </node>
    <node label="ں">
      <textCharAction />
    </node>
    <node label="ھ">
      <textCharAction />
    </node>
    <node label="ہ">
      <textCharAction />
    </node>
    <node label="و">
      <textCharAction />
    </node>
    <node label="ۄ">
      <textCharAction />
    </node>
    <node label="ۆ">
      <textCharAction />
    </node>
    <node label="ی">
      <textCharAction />
    </node>
    <node label="ؠ">
      <textCharAction />
    </node>
    <node label="ے">
      <textCharAction />
    </node>
  </group>
  <group name="Upper case" colorInfoName="upper case">
    <node label="ء">
      <textCharAction />
    </node>
    <node label="آ">
      <textCharAction />
    </node>
    <node label="أ">
      <textCharAction />
    </node>
    <node label="ٲ">
      <textCharAction />
    </node>
    <node label="ؤ">
      <textCharAction />
    </node>
    <node label="ا">
      <textCharAction />
    </node>
    <node label="ب">
      <textCharAction />
    </node>
    <node label="پ">
      <textCharAction />
    </node>
    <node label="ت">
      <textCharAction />
    </node>
    <node label="ث">
      <textCharAction />
    </node>
    <node label="ٹ">
      <textCharAction />
    </node>
    <node label="ج">
      <textCharAction />
    </node>
    <node label="چ">
      <textCharAction />
    </node>
    <node label="ح">
      <textCharAction />
    </node>
    <node label="خ">
      <textCharAction />
    </node>
    <node label="د">
      <textCharAction />
    </node>
    <node label="ذ">
      <textCharAction />
    </node>
    <node label="ڈ">
      <textCharAction />
    </node>
    <node label="ر">
      <textCharAction />
    </node>
    <node label="ز">
      <textCharAction />
    </node>
    <node label="ڑ">
      <textCharAction />
    </node>
    <node label="ژ">
      <textCharAction />
    </node>
    <node label="س">
      <textCharAction />
    </node>
    <node label="ش">
      <textCharAction />
    </node>
    <node label="ص">
      <textCharAction />
    </node>
    <node label="ض">
      <textCharAction />
    </node>
    <node label="ط">
      <textCharAction />
    </node>
    <node label="ظ">
      <textCharAction />
    </node>
    <node label="ع">
      <textCharAction />
    </node>
    <node label="غ">
      <textCharAction />
    </node>
    <node label="ف">
      <textCharAction />
    </node>
    <node label="ق">
      <textCharAction />
    </node>
    <node label="ک">
      <textCharAction />
    </node>
    <node label="گ">
      <textCharAction />
    </node>
    <node label="ل">
      <textCharAction />
    </node>
    <node label="م">
      <textCharAction />
    </node>
    <node label="ن">
      <textCharAction />
    </node>
    <node label="ں">
      <textCharAction />
    </node>
    <node label="ھ">
      <textCharAction />
    </node>
    <node label="ہ">
      <textCharAction />
    </node>
    <node label="و">
      <textCharAction />
    </node>
    <node label="ۄ">
      <textCharAction />
    </node>
    <node label="ۆ">
      <textCharAction />
    </node>
    <node label="ی">
      <textCharAction />
    </node>
    <node label="ؠ">
      <textCharAction />
    </node>
    <node label="ے">
      <textCharAction />
    </node>
  </group>
  <group name="paragraphSpace" colorInfoName="paragraphSpace">
    <node label="¶" text="&#10;">
      <textCharAction />
    </node>
    <node label="␣" text=" ">
      <textCharAction />
    </node>
  </group>
  <group name="Editing" colorInfoName="editing">
    <node label="⌫">
      <deleteTextAction distance="last char" />
    </node>
    <node label="⌦">
      <deleteTextAction distance="next char" />
    </node>
    <node label="⌫ Word">
      <deleteTextAction distance="last word" />
    </node>
  </group>
</alphabet>
